[package]
name = "finito-door"
version = "0.1.0"
authors = ["Vincent Ambo <vincent@aprila.no>"]

[dependencies]
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"

[dependencies.finito]
path = "../finito-core"
