[package]
name = "store-ref-scanner"
version = "0.1.0"
description = "scanner/extractor of Nix-like store paths from byte arrays/streams"
license = "MIT OR Apache-2.0"
categories = ["no-std", "parsing"]
edition = "2021"
homepage = "https://cs.tvl.fyi/depot/-/tree/users/fogti/store-ref-scanner"
include = ["/src"]

[dependencies]
